# Generated by Django 4.2.5 on 2024-12-02 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dsrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyakit',
            name='dokter',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penyakit',
            name='gambar',
            field=models.ImageField(null=True, upload_to='penyakit/'),
        ),
    ]
