# Generated by Django 4.2.5 on 2024-12-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_penyakit_dokter_penyakit_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riwayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateTimeField()),
                ('result', models.TextField()),
            ],
        ),
    ]
